### ISSUE TITLE
Deal with ASyTop error.

### ISSUE THREAD

**Issue by yakutovicha** [nanotech-empa/aiida-gaussian#12]
Sometimes, gaussian is not able to resolve the symmetry of a structure, which results in the following error:

```
 Logic error in ASyTop.
 Error termination via Lnk1e in /opt/g16_avx2/l202.exe at Wed Jan  5 10:16:12 2022.
```

An example of a simple input file that causes that is:
```
%chk=aiida.chk
%mem=13920MB
%nprocshared=1
#P uB3LYP/6-311G** empiricaldispersion=GD3 guess=mix opt=(maxstep=10) scf=(maxcycle=140)

input generated by the aiida-gaussian plugin

0 1
C 6.877573 5.937481 5.000001
C 5.546581 5.937481 5.000002
H 7.424154 6.874961 5.000004 -> 5.000003 to fix
H 7.424153 5.000000 5.000000
H 5.000000 6.874962 5.000000
H 5.000000 5.000000 5.000004 -> 5.000003 to fix
```

To do:

- [x] Parse the error and finish the calculation with `ERROR_ASYTOP` error (Done with #13).
- [x] #14

**Comment by eimrek** [comment]
It's not clear to me how to handle this though.

One option is to reduce the number of decimal places in the coordinates but in principle then the geometry is not exactly the same as inputted and this is something the user might not want to happen without them knowing. For example, very tiny symmetry breaking might be an intended key point in the input geometry. Therefore, I think it might make sense to let users deal with this error in their workflows as they see fit.

**Comment by yakutovicha** [comment]
I am also not sure whether we should try to handle this or just let the gaussian developers know about this issue. Do they have some kind of a bug tracker? It looks more like a bug to me, so I would probably just report it. What do you think?

**Comment by eimrek** [comment]
I think the most common gaussian license does not include bug fixes (just a specific, static revision). Therefore, even if they fix it, there will be a lot of users (us included) that will not get the fix. IMO, better to handle this in our higher-level workflows, as we don't really mind if the geometry gets changed a bit when this error occurs.

**Comment by yakutovicha** [comment]
Maybe a good idea then would be to add the handler, but make it optional. So the upper-level user-facing work chains can enable it if they want to.

The logic would be: if `ASyTop` exit code is detected - round the coordinate to the 5th digit. If detected again - except. I wouldn't go down to the 4th digit, but stick to this very simple logic. Should probably be good enough. Otherwise, we will extend it.

**Comment by eimrek** [comment]
Okay, that sounds good. Let's keep the handler off by default.

**Comment by yakutovicha** [comment]
All tasks addressed.
