### ISSUE TITLE
Gaussian: include symmetries if SCF fails

### ISSUE THREAD

**Issue by cpignedoli** [nanotech-empa/aiida-gaussian#16]
In an example of a Cu-containing molecule (see below) SCF fails:
https://github.com/nanotech-empa/aiida-nanotech-empa/blob/6405c4e9b4c8b22a09aca225a5dae9669951c093/aiida_nanotech_empa/workflows/gaussian/scf_workchain.py#L18
[structure-pk-22851.xyz.gz](https://github.com/nanotech-empa/aiida-nanotech-empa/files/9744308/structure-pk-22851.xyz.gz)

Adding symmetry to the input solves the problem (see the output below). Workflows should be updated according to this example.

[crlMSm2.log](https://github.com/nanotech-empa/aiida-nanotech-empa/files/9744260/crlMSm2.log)

**Comment by eimrek** [comment]
Could also just be the basis set that solves the issue. (Lanl2DZ instead of the usual Pople ones)

**Comment by yakutovicha** [comment]
> Could also just be the basis set that solves the issue. (Lanl2DZ instead of the usual Pople ones)

Indeed, the following input did the job for me:
```
%chk=aiida.chk
%mem=30000MB
%nprocshared=4
#N uB3LYP/Lanl2DZ scf=(maxcycle=300) sp

input generated by the aiida-gaussian plugin
```

**Comment by yakutovicha** [comment]
I just checked the setup @cpignedoli used: it seems to be related to the basis set. He used `6-31`.

**Comment by cpignedoli** [comment]
Since the issue was related to the basis set selection, not symmetries, I am going to close it.
