### ISSUE TITLE
Input file writing broken

### ISSUE THREAD

**Issue by ConradJohnston** [nanotech-empa/aiida-gaussian#30]
The writing of the input file by the `GaussianCalculation` `CalcJob` type is currently broken due to a bug in the Pymatgen `GaussianInput` `to_string()` method. 

I made [a report about this here](https://github.com/materialsproject/pymatgen/issues/2863).

A quick fix might be to put a constraint on the Pymatgen version in the dependencies? [v2022.11.7](https://github.com/materialsproject/pymatgen/releases/tag/v2022.11.7) and older should work.

**Comment by eimrek** [comment]
Thanks for reporting this! I capped the version as suggested.
