### ISSUE TITLE
`GaussianBaseParser` excepts if parsed output parameters contain `nan` or `inf`

### ISSUE THREAD

**Issue by sphuber** [nanotech-empa/aiida-gaussian#31]
The data parsed by `cclib.io.parse` from the stdout can contain `nan` and `inf` values, which cannot be stored in AiiDA's database. The parser is already aware of this problem:
https://github.com/nanotech-empa/aiida-gaussian/blob/f25f33ab9786baaf551a9b66287b54508489f295/aiida_gaussian/parsers/gaussian.py#L94

however, it only converts `nan` for the `scfvalues` key, but the dictionary can contain `nan` values in any of the other keys in the parsed dictionary as well. The conversion should be done recursively for all `np.arrays` in the parsed dictionary.

**Comment by sphuber** [comment]
You can assign me, I have a fix and am working on a PR. Just need to sort out a test for it.

**Comment by eimrek** [comment]
thanks @sphuber for the report and for working on this.

Is the plan to replace all `nan` values to 0? Could be misleading in some cases, but i don't really have a better idea at the moment. What about the `inf` values?

**Comment by sphuber** [comment]
The `nan_to_num` function is already being used in the current parser and by default it replaces `nan` indeed with `0.0`. I'd be happy to replace this with anything else. We could think of replacing it with a string placeholder, but I am not sure if `numpy` arrays allow to mix types. So maybe we have to use a float, in which case `0.0` might be our best choice.

As for `inf` and `-inf`, these are also automatically converted by `nan_to_num` and by default are replaced with a very large float and very large negative float. Typically something like `1E300`. Think this is fine to keep as behavior.

**Comment by eimrek** [comment]
thanks for the comment.

I reminded myself of the code a bit and here

https://github.com/nanotech-empa/aiida-gaussian/blob/f25f33ab9786baaf551a9b66287b54508489f295/aiida_gaussian/parsers/gaussian.py#L83-L97

`property_dict` contains just python dicts and lists, no numpy arrays.

The `nan` and `inf` values should be `float('nan')` and `float('inf')`, not the ones defined via numpy. I just used `np.nan_to_num` to easily convert that to `0.0`. As we don't have numpy arrays, converting `float("nan")` to just a string `"nan"` should be easy (same with `inf`).

I think i would prefer `nan` and `inf` to be replaced by strings instead of numbers. The `nan` can prevent a potential misunderstanding if a property was not calculated or failed to be not mixed up with a successful value of `0.0`. What do you think? 

Pinging also @yakutovicha @cpignedoli for comments.

**Comment by sphuber** [comment]
> property_dict contains just python dicts and lists, no numpy arrays.

Are you sure? That is not what I am seeing. For example `property_dict['scfvalues'][0]` is definitely of type `numpy.ndarray`.

> I think i would prefer nan and inf to be replaced by strings instead of numbers. The nan can prevent a potential misunderstanding if a property was not calculated or failed to be not mixed up with a successful value of 0.0. 

We won't be able to use [`numpy.nan_to_num`](https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html) for this as the replacement values needs to be castable to the `dtype` of the array, which in this case is `float64`, and so trying to replace with a string will except:

```python
In [32]: np.nan_to_num(np.array([1, 2, np.nan]), nan='nan')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[32], line 1
----> 1 np.nan_to_num(np.array([1, 2, np.nan]), nan='nan')

File <__array_function__ internals>:180, in nan_to_num(*args, **kwargs)

File ~/.virtualenvs/aiida_dev/lib/python3.8/site-packages/numpy/lib/type_check.py:518, in nan_to_num(x, copy, nan, posinf, neginf)
    516 idx_posinf = isposinf(d)
    517 idx_neginf = isneginf(d)
--> 518 _nx.copyto(d, nan, where=idx_nan)
    519 _nx.copyto(d, maxf, where=idx_posinf)
    520 _nx.copyto(d, minf, where=idx_neginf)

File <__array_function__ internals>:180, in copyto(*args, **kwargs)

TypeError: Cannot cast scalar from dtype('<U3') to dtype('float64') according to the rule 'same_kind'
```

That being said though, the numpy arrays will eventually anyway be converted to plain Python lists by AiiDA before being stored in the database. So if we do the conversion ourselves, we could opt to mix types and replace `nan` and `inf` with stringized versions. There are just two potential downsides

1. This is breaking the current behavior which uses the default behavior of `nan_to_num` which converts `nan` to `0.0` and `inf` to a large float.
2. A user that loads the `Dict` from the database won't be able to easily convert any of the lists to a `numpy` array since it has mixed types and so will have to use a manual (recursive) conversion method.

I do agree though that it might still be preferable over having `0.0` and not being sure if that corresponds to an actual zero or a converted `nan`.

**Comment by eimrek** [comment]
you're right. cclib indeed returns numpy arrays with potentially `np.nan` values. my check was a bit too hasty

Both of your points make sense. True, it would be bad to break current behaviour and very annoying to explicitly check for these strings.

Ok, i'm convinced. let's keep the current behavior but just expand it to the whole output dictionary.
