### ISSUE TITLE
Cannot run GaussianCalculations with newer versions of pymatgen

### ISSUE THREAD

**Issue by kmlefran** [nanotech-empa/aiida-gaussian#40]
# Description
Currently, in `aiida_gaussian/calculations/gaussian.py`, line 221, the pymatgen `GaussianInput.to_string()` method is called. However, after pymatgen version 2023.12.18, the `to_string` method was removed and instead `to_str` should be used.

Therefore, newer versions of pymatgen cannot be used without errors being raised. However, newer versions are allowed in the dependencies of pyproject.toml, "pymatgen>=2022.1.20"

# Issue
Attempting to run `GaussianCalculation`s with newer versions of pymatgen raises errors.

# Fix
Replace `to_string` with `to_str` on `aiida_gaussian/calculations/gaussian.py`, line 221

**Comment by kmlefran** [comment]
Oh I just saw you had a pull request related to this, sorry if the issue was not needed

**Comment by eimrek** [comment]
Thanks for the reminder! should be fixed now.
